# This script was generated by OpenMM-Setup on 2026-01-26.

from openmm import *
from openmm.app import *
from openmm.unit import *

# Input Files

pdb = PDBFile('mixture_ready.pdb')
forcefield = ForceField('amber19-all.xml', 'amber19/tip3pfb.xml')

# System Configuration

nonbondedMethod = CutoffNonPeriodic
nonbondedCutoff = 1.0*nanometers
ewaldErrorTolerance = 0.0005
constraints = HBonds
rigidWater = True
constraintTolerance = 0.000001
hydrogenMass = 1.5*amu

# Integration Options

dt = 0.004*picoseconds
temperature = 300*kelvin
friction = 1.0/picosecond
pressure = 1.0*atmospheres
barostatInterval = 25

# Simulation Options

steps = 1000000
equilibrationSteps = 1000
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'single'}
dcdReporter = DCDReporter('trajectory.dcd', 10000)
dataReporter = StateDataReporter('log.txt', 1000, totalSteps=steps,
    step=True, speed=True, progress=True, potentialEnergy=True, temperature=True, separator='\t')
checkpointReporter = CheckpointReporter('checkpoint.chk', 10000)

# Prepare the Simulation

print('Building system...')
topology = pdb.topology
positions = pdb.positions
system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
    constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance, hydrogenMass=hydrogenMass)
# --- Add soft repulsive walls (non-penetrable box) ---

wall = CustomExternalForce(
    "step(x-xmax)*k*(x-xmax)^2 + step(xmin-x)*k*(xmin-x)^2 +"
    "step(y-ymax)*k*(y-ymax)^2 + step(ymin-y)*k*(ymin-y)^2 +"
    "step(z-zmax)*k*(z-zmax)^2 + step(zmin-z)*k*(zmin-z)^2"
)

wall.addGlobalParameter("k", 1000*kilojoule_per_mole/nanometer**2)

# Box dimensions: 40 x 40 x 80 nm
wall.addGlobalParameter("xmin", 0*nanometer)
wall.addGlobalParameter("xmax", 40*nanometer)
wall.addGlobalParameter("ymin", 0*nanometer)
wall.addGlobalParameter("ymax", 40*nanometer)
wall.addGlobalParameter("zmin", 0*nanometer)
wall.addGlobalParameter("zmax", 80*nanometer)

for i in range(system.getNumParticles()):
    wall.addParticle(i, [])

system.addForce(wall)
integrator = LangevinMiddleIntegrator(temperature, friction, dt)
integrator.setConstraintTolerance(constraintTolerance)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)

# Minimize and Equilibrate

print('Performing energy minimization...')
simulation.minimizeEnergy()
print('Equilibrating...')
simulation.context.setVelocitiesToTemperature(temperature)
simulation.step(equilibrationSteps)

# Simulate

print('Simulating...')
simulation.reporters.append(dcdReporter)
simulation.reporters.append(dataReporter)
simulation.reporters.append(checkpointReporter)
simulation.currentStep = 0
simulation.step(steps)